name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    name: test with JDK ${{ matrix.java }}
    steps:
      - name: check out code
        uses: actions/checkout@v3.5.0
        with:
          persist-credentials: false
      - name: set up JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      - name: validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - uses: burrunan/gradle-cache-action@v1
        name: build project
        with:
          job-id: jdk-${{ matrix.java }}
          arguments: build
          concurrent: true
