name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    name: test with JDK ${{ matrix.java }}
    steps:
      - name: check out code
        uses: actions/checkout@v3.4.0
        with:
          persist-credentials: false
      - name: set up JDK
        uses: actions/setup-java@v3.10.0
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      - uses: burrunan/gradle-cache-action@v1
        name: build project
        with:
          job-id: jdk-${{ matrix.java }}
          arguments: build
          concurrent: true
