name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: check out code
        uses: actions/checkout@v3.4.0
        with:
          persist-credentials: false
      - name: set up JDK
        uses: actions/setup-java@v3.10.0
        with:
          distribution: zulu
          java-version: 11
      - name: validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: publish package
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSPHRASE }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_TOKEN }}
