name: validate config

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: validate Renovate config
        uses: rinchsan/renovate-config-validator@v0.0.12
